# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

City.create(name: 'Los Angeles', country: 'United States')
City.create(name: 'Mar Del Plata', country: 'Argentina')
City.create(name: 'Rio de Janeiro', country: 'Brazil')
City.create(name: 'New York City', country: 'United States')
City.create(name: 'Buenos Aires', country: 'Argenina')
City.create(name: 'Santiago', country: 'Chile')
City.create(name: 'Bogota', country: 'Colombia')
City.create(name: 'Caracas', country: 'Venezuela')
City.create(name: 'Kingston', country: 'Jamaica')
City.create(name: 'Barcelona', country: 'Spain')
City.create(name: 'Moscow', country: 'Russia')
City.create(name: 'Miami', country: 'United States')
City.create(name: 'Chicago', country: 'United States')
City.create(name: 'Seattle', country: 'United States')
City.create(name: 'Berlin', country: 'Germany')
City.create(name: 'Austin', country: 'United States')
City.create(name: 'Mumbai', country: 'India')
City.create(name: 'Nashville', country: 'United States')
City.create(name: 'Atlanta', country: 'United States')
City.create(name: 'San Juan', country: 'Puerto Rico')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
City.create(name: 'San Francisco', country: 'United States')
